### ISSUE TITLE
dxf format

### ISSUE THREAD

**Issue by PowPodg** [Jack000/Deepnest#50]
DXF files are not read correctly - all information in DXF is not taken into account

**Comment by deece** [comment]
Could you please be more specific about what is missed?

Also, make sure it's note a dupe of #10, #35 or #47

**Comment by olegiv1** [comment]
Try the (attach - 2.dxf) file and see for yourself.Converter can not determine where the boundaries of the shape.Sometimes one wigura is placed on another.I'm trying to fix it, but I still can not build a project (I try in VS 2017)  15.02.2019, 03:09, "deece" <notifications@github.com>:Could you please be more specific about what is missed?Also, make sure it's note a dupe of #10, #35 or #47—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.  -- Respectfully,Oleg I.

**Comment by PowPodg** [comment]
Try the (attach - 2.dxf) file and see for yourself.
Converter can not determine where the boundaries of the shape.
Sometimes one wigura is placed on another.
I'm trying to fix it, but I still can not build a project (I try in VS 2017)

**Comment by deece** [comment]
I'm on a phone atm, but check to make sure your shape is a closed path.

**Comment by PowPodg** [comment]
In the program - Grafis - this file is recognized normally
[2.zip](https://github.com/Jack000/Deepnest/files/2868098/2.zip)

**Comment by PowPodg** [comment]
Why in debug mode, get the other sizes when you import data from DXF file?
